import Foundation

struct EmojiCategory: Identifiable {
    let id: String
    let name: String
    let icon: String
    let emojis: [EmojiItem]
}

struct EmojiItem: Identifiable, Hashable {
    let id: String
    let emoji: String
    let keywords: [String]

    init(_ emoji: String, _ keywords: [String] = []) {
        self.id = emoji
        self.emoji = emoji
        self.keywords = keywords
    }
}

enum EmojiData {
    static let categories: [EmojiCategory] = [
        EmojiCategory(id: "smileys", name: "Smileys & People", icon: "face.smiling", emojis: smileys),
        EmojiCategory(id: "animals", name: "Animals & Nature", icon: "leaf", emojis: animals),
        EmojiCategory(id: "food", name: "Food & Drink", icon: "fork.knife", emojis: food),
        EmojiCategory(id: "travel", name: "Travel & Places", icon: "car", emojis: travel),
        EmojiCategory(id: "activities", name: "Activities", icon: "sportscourt", emojis: activities),
        EmojiCategory(id: "objects", name: "Objects", icon: "lightbulb", emojis: objects),
        EmojiCategory(id: "symbols", name: "Symbols", icon: "heart", emojis: symbols),
        EmojiCategory(id: "flags", name: "Flags", icon: "flag", emojis: flags),
    ]

    static let smileys: [EmojiItem] = [
        EmojiItem("😀", ["grinning", "happy", "smile"]),
        EmojiItem("😃", ["smiley", "happy"]),
        EmojiItem("😄", ["smile", "happy"]),
        EmojiItem("😁", ["grin", "happy"]),
        EmojiItem("😅", ["sweat", "smile"]),
        EmojiItem("😂", ["joy", "laugh", "crying"]),
        EmojiItem("🤣", ["rofl", "laugh"]),
        EmojiItem("😊", ["blush", "happy"]),
        EmojiItem("😇", ["innocent", "angel"]),
        EmojiItem("🙂", ["slight smile"]),
        EmojiItem("😉", ["wink"]),
        EmojiItem("😍", ["heart eyes", "love"]),
        EmojiItem("🥰", ["love", "hearts"]),
        EmojiItem("😘", ["kiss"]),
        EmojiItem("😎", ["cool", "sunglasses"]),
        EmojiItem("🤓", ["nerd", "geek"]),
        EmojiItem("🧐", ["monocle"]),
        EmojiItem("🤔", ["thinking", "hmm"]),
        EmojiItem("🤗", ["hug"]),
        EmojiItem("😐", ["neutral"]),
        EmojiItem("😑", ["expressionless"]),
        EmojiItem("😶", ["silent", "mute"]),
        EmojiItem("🙄", ["eye roll"]),
        EmojiItem("😏", ["smirk"]),
        EmojiItem("😴", ["sleep", "zzz"]),
        EmojiItem("🤤", ["drool"]),
        EmojiItem("😷", ["mask", "sick"]),
        EmojiItem("🤧", ["sneeze"]),
        EmojiItem("🥳", ["party", "celebrate"]),
        EmojiItem("🤩", ["star struck"]),
        EmojiItem("😤", ["triumph"]),
        EmojiItem("😡", ["angry", "rage"]),
        EmojiItem("🥶", ["cold", "freezing"]),
        EmojiItem("🥵", ["hot"]),
        EmojiItem("😱", ["scream", "fear"]),
        EmojiItem("😈", ["devil", "evil"]),
        EmojiItem("👻", ["ghost"]),
        EmojiItem("💀", ["skull", "death"]),
        EmojiItem("🤖", ["robot"]),
        EmojiItem("👽", ["alien"]),
        EmojiItem("👋", ["wave", "hello"]),
        EmojiItem("🤚", ["raised hand"]),
        EmojiItem("✋", ["hand", "stop"]),
        EmojiItem("👌", ["ok"]),
        EmojiItem("✌️", ["peace", "victory"]),
        EmojiItem("🤞", ["fingers crossed", "luck"]),
        EmojiItem("👍", ["thumbs up", "like"]),
        EmojiItem("👎", ["thumbs down", "dislike"]),
        EmojiItem("👏", ["clap"]),
        EmojiItem("🙌", ["hooray", "hands"]),
        EmojiItem("💪", ["strong", "muscle"]),
        EmojiItem("🧠", ["brain", "smart"]),
        EmojiItem("👀", ["eyes", "look"]),
        EmojiItem("👁️", ["eye"]),
        EmojiItem("👤", ["person", "user"]),
        EmojiItem("👥", ["people", "users", "team"]),
    ]

    static let animals: [EmojiItem] = [
        EmojiItem("🐶", ["dog", "puppy"]),
        EmojiItem("🐱", ["cat", "kitten"]),
        EmojiItem("🐭", ["mouse"]),
        EmojiItem("🐹", ["hamster"]),
        EmojiItem("🐰", ["rabbit", "bunny"]),
        EmojiItem("🦊", ["fox"]),
        EmojiItem("🐻", ["bear"]),
        EmojiItem("🐼", ["panda"]),
        EmojiItem("🐸", ["frog"]),
        EmojiItem("🐵", ["monkey"]),
        EmojiItem("🐔", ["chicken"]),
        EmojiItem("🐧", ["penguin"]),
        EmojiItem("🐦", ["bird"]),
        EmojiItem("🦅", ["eagle"]),
        EmojiItem("🦉", ["owl"]),
        EmojiItem("🦄", ["unicorn"]),
        EmojiItem("🐝", ["bee", "honey"]),
        EmojiItem("🐛", ["bug", "caterpillar"]),
        EmojiItem("🦋", ["butterfly"]),
        EmojiItem("🐙", ["octopus"]),
        EmojiItem("🐠", ["fish", "tropical"]),
        EmojiItem("🐳", ["whale"]),
        EmojiItem("🐬", ["dolphin"]),
        EmojiItem("🦈", ["shark"]),
        EmojiItem("🌲", ["tree", "evergreen"]),
        EmojiItem("🌳", ["tree", "deciduous"]),
        EmojiItem("🌴", ["palm tree"]),
        EmojiItem("🌵", ["cactus"]),
        EmojiItem("🌱", ["seedling", "sprout", "grow"]),
        EmojiItem("🌿", ["herb", "leaf"]),
        EmojiItem("🍀", ["clover", "luck"]),
        EmojiItem("🌸", ["cherry blossom", "flower"]),
        EmojiItem("🌺", ["hibiscus", "flower"]),
        EmojiItem("🌻", ["sunflower"]),
        EmojiItem("🌹", ["rose"]),
        EmojiItem("🌷", ["tulip"]),
        EmojiItem("🌊", ["wave", "ocean", "water"]),
        EmojiItem("❄️", ["snowflake", "cold", "winter"]),
        EmojiItem("🔥", ["fire", "hot", "lit"]),
        EmojiItem("⭐", ["star"]),
        EmojiItem("🌟", ["glowing star"]),
        EmojiItem("✨", ["sparkles", "magic"]),
        EmojiItem("⚡", ["lightning", "bolt", "electric"]),
        EmojiItem("☀️", ["sun", "sunny"]),
        EmojiItem("🌙", ["moon", "crescent"]),
        EmojiItem("🌈", ["rainbow"]),
        EmojiItem("☁️", ["cloud"]),
        EmojiItem("🌤️", ["sun behind cloud"]),
    ]

    static let food: [EmojiItem] = [
        EmojiItem("🍎", ["apple", "red"]),
        EmojiItem("🍊", ["orange", "tangerine"]),
        EmojiItem("🍋", ["lemon"]),
        EmojiItem("🍇", ["grapes"]),
        EmojiItem("🍓", ["strawberry"]),
        EmojiItem("🍑", ["peach"]),
        EmojiItem("🍒", ["cherry"]),
        EmojiItem("🥑", ["avocado"]),
        EmojiItem("🍕", ["pizza"]),
        EmojiItem("🍔", ["hamburger", "burger"]),
        EmojiItem("🌮", ["taco"]),
        EmojiItem("🍜", ["ramen", "noodles"]),
        EmojiItem("🍣", ["sushi"]),
        EmojiItem("🍰", ["cake", "dessert"]),
        EmojiItem("🧁", ["cupcake"]),
        EmojiItem("🍩", ["donut", "doughnut"]),
        EmojiItem("🍪", ["cookie"]),
        EmojiItem("☕", ["coffee", "hot"]),
        EmojiItem("🍵", ["tea"]),
        EmojiItem("🧃", ["juice"]),
        EmojiItem("🍺", ["beer"]),
        EmojiItem("🍷", ["wine"]),
        EmojiItem("🥤", ["cup", "drink"]),
    ]

    static let travel: [EmojiItem] = [
        EmojiItem("🏠", ["home", "house"]),
        EmojiItem("🏡", ["house", "garden"]),
        EmojiItem("🏢", ["office", "building"]),
        EmojiItem("🏗️", ["construction"]),
        EmojiItem("🏰", ["castle"]),
        EmojiItem("🏥", ["hospital"]),
        EmojiItem("🏫", ["school"]),
        EmojiItem("🏛️", ["museum", "classical"]),
        EmojiItem("⛪", ["church"]),
        EmojiItem("🕌", ["mosque"]),
        EmojiItem("🌐", ["globe", "web", "internet", "world"]),
        EmojiItem("🗺️", ["map", "world"]),
        EmojiItem("🌍", ["earth", "world", "globe"]),
        EmojiItem("🌎", ["earth", "americas"]),
        EmojiItem("🌏", ["earth", "asia"]),
        EmojiItem("🚀", ["rocket", "launch", "space"]),
        EmojiItem("✈️", ["airplane", "travel", "flight"]),
        EmojiItem("🚁", ["helicopter"]),
        EmojiItem("🚂", ["train", "locomotive"]),
        EmojiItem("🚗", ["car", "automobile"]),
        EmojiItem("🚕", ["taxi"]),
        EmojiItem("🚌", ["bus"]),
        EmojiItem("🚲", ["bicycle", "bike"]),
        EmojiItem("⛵", ["sailboat"]),
        EmojiItem("🛳️", ["cruise", "ship"]),
        EmojiItem("🏖️", ["beach"]),
        EmojiItem("🏔️", ["mountain", "snow"]),
        EmojiItem("⛰️", ["mountain"]),
        EmojiItem("🗼", ["tower"]),
        EmojiItem("🗽", ["statue of liberty"]),
    ]

    static let activities: [EmojiItem] = [
        EmojiItem("⚽", ["soccer", "football"]),
        EmojiItem("🏀", ["basketball"]),
        EmojiItem("🏈", ["football", "american"]),
        EmojiItem("⚾", ["baseball"]),
        EmojiItem("🎾", ["tennis"]),
        EmojiItem("🏐", ["volleyball"]),
        EmojiItem("🏓", ["ping pong", "table tennis"]),
        EmojiItem("🥊", ["boxing"]),
        EmojiItem("🏋️", ["gym", "weight", "exercise"]),
        EmojiItem("🧘", ["yoga", "meditation"]),
        EmojiItem("🏊", ["swimming", "pool"]),
        EmojiItem("🚴", ["cycling", "bike"]),
        EmojiItem("🎮", ["gaming", "video game", "controller"]),
        EmojiItem("🎲", ["dice", "game"]),
        EmojiItem("🧩", ["puzzle"]),
        EmojiItem("🎯", ["target", "dart", "bullseye"]),
        EmojiItem("🎨", ["art", "palette", "paint", "creative"]),
        EmojiItem("🎭", ["theater", "drama"]),
        EmojiItem("🎬", ["movie", "film", "clapper"]),
        EmojiItem("🎤", ["microphone", "karaoke", "sing"]),
        EmojiItem("🎵", ["music", "note"]),
        EmojiItem("🎶", ["music", "notes"]),
        EmojiItem("🎸", ["guitar"]),
        EmojiItem("🎹", ["piano", "keyboard"]),
        EmojiItem("🎺", ["trumpet"]),
        EmojiItem("🏆", ["trophy", "winner", "champion"]),
        EmojiItem("🥇", ["gold medal", "first"]),
        EmojiItem("🥈", ["silver medal", "second"]),
        EmojiItem("🥉", ["bronze medal", "third"]),
        EmojiItem("🎪", ["circus", "tent"]),
    ]

    static let objects: [EmojiItem] = [
        EmojiItem("💼", ["briefcase", "business", "work"]),
        EmojiItem("📁", ["folder", "file"]),
        EmojiItem("📂", ["folder", "open"]),
        EmojiItem("📚", ["books", "library", "study"]),
        EmojiItem("📖", ["book", "open", "read"]),
        EmojiItem("📝", ["note", "memo", "write"]),
        EmojiItem("📋", ["clipboard"]),
        EmojiItem("📌", ["pin", "pushpin"]),
        EmojiItem("📎", ["paperclip"]),
        EmojiItem("🔗", ["link", "chain"]),
        EmojiItem("💡", ["lightbulb", "idea"]),
        EmojiItem("🔧", ["wrench", "tool"]),
        EmojiItem("🔨", ["hammer", "tool"]),
        EmojiItem("⚙️", ["gear", "settings", "cog"]),
        EmojiItem("🔬", ["microscope", "science", "research"]),
        EmojiItem("🔭", ["telescope", "astronomy"]),
        EmojiItem("💻", ["laptop", "computer"]),
        EmojiItem("🖥️", ["desktop", "computer", "monitor"]),
        EmojiItem("📱", ["phone", "mobile"]),
        EmojiItem("⌨️", ["keyboard"]),
        EmojiItem("🖨️", ["printer"]),
        EmojiItem("📷", ["camera", "photo"]),
        EmojiItem("🎥", ["movie camera", "film"]),
        EmojiItem("📺", ["tv", "television"]),
        EmojiItem("📻", ["radio"]),
        EmojiItem("🔑", ["key"]),
        EmojiItem("🗝️", ["old key"]),
        EmojiItem("🔒", ["lock", "secure"]),
        EmojiItem("🔓", ["unlock", "open"]),
        EmojiItem("🛡️", ["shield", "security"]),
        EmojiItem("💎", ["gem", "diamond"]),
        EmojiItem("💰", ["money", "bag"]),
        EmojiItem("💳", ["credit card", "payment"]),
        EmojiItem("✉️", ["envelope", "email", "mail"]),
        EmojiItem("📧", ["email", "mail"]),
        EmojiItem("📦", ["package", "box"]),
        EmojiItem("🏷️", ["tag", "label"]),
        EmojiItem("🔔", ["bell", "notification"]),
        EmojiItem("🔕", ["mute", "no bell"]),
        EmojiItem("📢", ["loudspeaker", "announcement"]),
    ]

    static let symbols: [EmojiItem] = [
        EmojiItem("❤️", ["heart", "love", "red"]),
        EmojiItem("🧡", ["heart", "orange"]),
        EmojiItem("💛", ["heart", "yellow"]),
        EmojiItem("💚", ["heart", "green"]),
        EmojiItem("💙", ["heart", "blue"]),
        EmojiItem("💜", ["heart", "purple"]),
        EmojiItem("🖤", ["heart", "black"]),
        EmojiItem("🤍", ["heart", "white"]),
        EmojiItem("💗", ["growing heart", "pink"]),
        EmojiItem("🩵", ["heart", "light blue"]),
        EmojiItem("✅", ["check", "done", "yes"]),
        EmojiItem("❌", ["cross", "no", "wrong"]),
        EmojiItem("⭕", ["circle"]),
        EmojiItem("❗", ["exclamation"]),
        EmojiItem("❓", ["question"]),
        EmojiItem("💯", ["100", "perfect", "score"]),
        EmojiItem("🔴", ["red circle"]),
        EmojiItem("🟠", ["orange circle"]),
        EmojiItem("🟡", ["yellow circle"]),
        EmojiItem("🟢", ["green circle"]),
        EmojiItem("🔵", ["blue circle"]),
        EmojiItem("🟣", ["purple circle"]),
        EmojiItem("⚪", ["white circle"]),
        EmojiItem("⚫", ["black circle"]),
        EmojiItem("🔶", ["diamond", "orange"]),
        EmojiItem("🔷", ["diamond", "blue"]),
        EmojiItem("▶️", ["play"]),
        EmojiItem("⏸️", ["pause"]),
        EmojiItem("⏹️", ["stop"]),
        EmojiItem("♻️", ["recycle", "green"]),
        EmojiItem("⚠️", ["warning", "caution"]),
        EmojiItem("🚫", ["prohibited", "forbidden"]),
        EmojiItem("♾️", ["infinity"]),
        EmojiItem("🔄", ["arrows", "refresh", "sync"]),
        EmojiItem("➕", ["plus", "add"]),
        EmojiItem("➖", ["minus", "subtract"]),
    ]

    static let flags: [EmojiItem] = [
        EmojiItem("🏁", ["checkered flag", "finish"]),
        EmojiItem("🚩", ["red flag"]),
        EmojiItem("🏳️", ["white flag"]),
        EmojiItem("🏴", ["black flag"]),
        EmojiItem("🏳️‍🌈", ["rainbow flag", "pride"]),
        EmojiItem("🇺🇸", ["usa", "united states", "america"]),
        EmojiItem("🇬🇧", ["uk", "united kingdom", "britain"]),
        EmojiItem("🇫🇷", ["france", "french"]),
        EmojiItem("🇩🇪", ["germany", "german"]),
        EmojiItem("🇪🇸", ["spain", "spanish"]),
        EmojiItem("🇮🇹", ["italy", "italian"]),
        EmojiItem("🇯🇵", ["japan", "japanese"]),
        EmojiItem("🇰🇷", ["korea", "korean"]),
        EmojiItem("🇨🇳", ["china", "chinese"]),
        EmojiItem("🇮🇳", ["india", "indian"]),
        EmojiItem("🇧🇷", ["brazil", "brazilian"]),
        EmojiItem("🇨🇦", ["canada", "canadian"]),
        EmojiItem("🇦🇺", ["australia", "australian"]),
        EmojiItem("🇲🇽", ["mexico", "mexican"]),
        EmojiItem("🇷🇺", ["russia", "russian"]),
        EmojiItem("🇸🇪", ["sweden", "swedish"]),
        EmojiItem("🇨🇭", ["switzerland", "swiss"]),
        EmojiItem("🇳🇱", ["netherlands", "dutch"]),
        EmojiItem("🇵🇹", ["portugal", "portuguese"]),
    ]

    static func search(_ query: String) -> [EmojiItem] {
        let lowered = query.lowercased()
        return categories.flatMap(\.emojis).filter { item in
            item.emoji.contains(lowered)
                || item.keywords.contains(where: { $0.contains(lowered) })
        }
    }
}
